USE [master]
GO

/****** Object:  Database [FileAnyTypesToDb]    Script Date: 4/3/2022 8:53:29 PM ******/
CREATE DATABASE [FileAnyTypesToDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FileAnyTypesToDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FileAnyTypesToDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FileAnyTypesToDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FileAnyTypesToDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FileAnyTypesToDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FileAnyTypesToDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FileAnyTypesToDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FileAnyTypesToDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FileAnyTypesToDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FileAnyTypesToDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [FileAnyTypesToDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FileAnyTypesToDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FileAnyTypesToDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FileAnyTypesToDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FileAnyTypesToDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FileAnyTypesToDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FileAnyTypesToDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FileAnyTypesToDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FileAnyTypesToDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FileAnyTypesToDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FileAnyTypesToDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FileAnyTypesToDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FileAnyTypesToDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FileAnyTypesToDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FileAnyTypesToDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FileAnyTypesToDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FileAnyTypesToDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FileAnyTypesToDb] SET RECOVERY FULL 
GO

ALTER DATABASE [FileAnyTypesToDb] SET  MULTI_USER 
GO

ALTER DATABASE [FileAnyTypesToDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FileAnyTypesToDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FileAnyTypesToDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FileAnyTypesToDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FileAnyTypesToDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FileAnyTypesToDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [FileAnyTypesToDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FileAnyTypesToDb] SET  READ_WRITE 
GO


